# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
# Installing dependencies
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir: '$(System.DefaultWorkingDirectory)'

# Run build
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      customCommand: run build

# Runnnig tests
  - script: |
      npx --no-install ng test --watch=false --reporters=progress,junit
# Runnning e2e tests
  - task: Npm@1
    inputs:
      command: custom
      customCommand: 'run e2e'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TESTS-*.xml'
