trigger: none

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  chromeDriverVersion: '80.0.3987.106'

steps:
# Installing dependencies
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir: '$(System.DefaultWorkingDirectory)'

# Run build
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      customCommand: run build

# Runnnig tests
  - script: |
      npx --no-install ng test --watch=false --reporters=progress,junit
    displayName: 'ng test'

# Changing version of chromedriver
  - script: |
      node node_modules/.bin/webdriver-manager update --versions.chrome=$(chromeDriverVersion) --gecko false --standalone false
    displayName: 'changing version of chromedriver to $(chromeDriverVersion)'

# Runnning e2e tests
  - script: |
      npx --no-install ng e2e --webdriverUpdate=false
    displayName: 'ng e2e tests'
  - task: PublishTestResults@2
    displayName: 'Publishing test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TESTS-*.xml'

  - publish: 'www/'
    artifact: 'www'
    displayName: 'Publishing Artifact'