# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  supportedChromeVersion: '80.0.3987.106'

steps:
# Installing dependencies
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir: '$(System.DefaultWorkingDirectory)'

# Run build
  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: custom
      customCommand: run build

# Runnnig tests
  - script: |
      npx --no-install ng test --watch=false --reporters=progress,junit
    displayName: 'ng test'
# Changing version of chromedriver
  - script: |
      node node_modules/.bin/webdriver-manager update --versions.chrome=$(supportedChromeVersion) 
    displayName: 'Changing version of chromedriver to $(supportedChromeVersion)'
# Runnning e2e tests
  - task: Npm@1
    displayName: 'npm run e2e'
    inputs:
      command: custom
      customCommand: 'run e2e'
  - task: PublishTestResults@2
    displayName: 'Publishing test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TESTS-*.xml'

  - publish: 'www/**'
    artifact: 'dist'
    displayName: 'Publishing Artifact'